steps:
# unit tests
- name: 'golang:latest'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'export GO111MODULE=on; go mod download; go test ./... -v'

# build container
# PROJECT_ID, SHORT_SHA variables are automatically by Cloud Build
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/goda:$SHORT_SHA'
  - '.'

# pushes image gcr
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/goda:$SHORT_SHA'

# gen manifest
- name: 'gcr.io/cloud-builders/gcloud'
  id: Manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
      sed -e 's/RELEASE_PROJECT/s9-demo/g' deployments/service.yaml | \
      sed -e 's/RELEASE_SHA/123456/g' > deployments/manifest.yaml

# pushes knative cluster
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'deployments/manifest.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kn-v3-head'